### PR TITLE
feat: add grafana server role

### PR DESCRIPTION
**Pull request by gardar**
Migration of https://github.com/cloudalchemy/ansible-grafana role as discussed in #45 

fixes: #45

### CODE REVIEW

**Comment by gardar** [comment]
@paulfantom probably need you to sign the CLA as well

**Comment by gardar** [comment]
@ishanjainn Ready for review

**Comment by ishanjainn** [comment]
Ill take a look, Can you merge main into this branch?

**Comment by gardar** [comment]
@ishanjainn sure, rebased.

**Comment by ishanjainn** [comment]
LGTM
Thanks for this PR!
Ill wait if @v-zhuravlev has any thoughts, If not, lll merge this by this week

**Comment by SuperQ** [comment]
Please create a tag / release and publish this to ansible galaxy.

**Pull request merged**
