### PR TITLE
Allow to include the Loki & Promtail roles with a tag

### PR DESCRIPTION
**Pull request by loliee**
Allow to include the Loki & Promtail roles with a tag.

This modification does not introduce a breaking change and fix an issue when including those roles with a tag, in this case the `uninstall.yml` file is always executed.

## Versions

- ansible: `[core 2.16.5]`
- grafana-ansible-collection: `5.3.0`

## Tests

You can check those tests to understand, reproduce the observed behavior:

```yaml
# playbook-test.yml

- hosts: localhost
  connection: local
  roles:
    - { role: example, tags: loki }
```

```yaml
# example/tasks/main.yml

- name: Deploy Loki service
  ansible.builtin.debug:
    msg: Include deploy.yml
  tags: loki_deploy

- name: Uninstall Loki service (Current version)
  ansible.builtin.debug:
    msg: Include uninstall.yml
  tags: [never, loki_uninstall]

- name: Uninstall Loki service (New version)
  ansible.builtin.debug:
    msg: Include uninstall.yml
  when: "'loki_uninstall' in ansible_run_tags"
  tags: always
```

## Running without tags

When running the playbook without tag the uninstall action is not executed, everything works as expected.

``` console
$ ansible-playbook playbook-test.yml

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [example : Deploy Loki service] ***********************************************************************************
ok: [localhost] => {
    "msg": "Include deploy.yml"
}

TASK [example : Uninstall Loki service (New version)] ******************************************************************
skipping: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

## Running with the role's tag (defined in the playbook) 💥

This is the problematic use case because Loki is installed and uninstalled:

```console
$ ansible-playbook playbook-test.yml -t loki

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [example : Deploy Loki service] ***********************************************************************************
ok: [localhost] => {
    "msg": "Include deploy.yml"
}

TASK [example : Uninstall Loki service (Current version)] **************************************************************
ok: [localhost] => {
    "msg": "Include uninstall.yml"
}

TASK [example : Uninstall Loki service (New version)] ******************************************************************
skipping: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

But we can see that the new version works as expected, the task is skipped.

## Running with the uninstall tag (defined in the role)

The uninstall also works as expected:

```console
$ ansible-playbook playbook-test.yml -t loki_uninstall

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [example : Uninstall Loki service (Current version)] **************************************************************
ok: [localhost] => {
    "msg": "Include uninstall.yml"
}

TASK [example : Uninstall Loki service (New version)] ******************************************************************
ok: [localhost] => {
    "msg": "Include uninstall.yml"
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by voidquark** [comment]
Hello @loliee,

I don't believe any changes are necessary. I re-tested using the latest collection version on a test VM with Ansible core 2.16.8, and each tag worked as expected. I recommend checking the [documentation regarding the never tag](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#always-and-never), as it functions as intended.

Here is a sample playbook for testing:
```bash
- name: Deploy Loki using the default configuration
  hosts: loki
  become: true
  roles:
    - role: grafana.grafana.loki
```

Execute the playbook without any tags to automatically trigger Loki deployment. Note that the uninstall task is not included in this operation. It works as expected:

```
ansible-playbook -i hosts loki_play.yml
```

Execute the playbook with the loki_deploy tag to run only the deployment task. The uninstall task is not included or executed:
```
ansible-playbook -i hosts loki_play.yml -t loki_deploy
```

Execute the playbook with the loki_uninstall tag to run only the uninstall task. In this case, the deployment task is not executed:
```
ansible-playbook -i hosts loki_play.yml -t loki_uninstall
```

I believe we can close this issue since there are no changes needed. If you want to correct a small typo in `name: Remove Loki directories"`, please raise a new PR to fix it.

**Comment by loliee** [comment]
In your example you don't add a tag in the role as I did…

I agree this is a weird behavior, that's why I add a small and simple example to analyze and reproduce this behavior.

**Comment by voidquark** [comment]
It seems there might be a misunderstanding about how tags are applied. You are adding new tags at the [role level](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#adding-tags-to-roles). If you want to add new tags this way in your setup, that's fine.

The role has two tags: `loki_deploy` and `loki_uninstall`, and they work as expected. You can find more details on how to [run tags with a playbook](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#selecting-or-skipping-tags-when-you-run-a-playbook).

**Comment by voidquark** [comment]
> > You are adding new tags at the [role level](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#adding-tags-to-roles). If you want to add new tags this way in your setup, that's fine.

When you incorporate a role in your playbook statically with the `roles` keyword, Ansible adds any tags you define to all the tasks in the role. 

For example:
```
 - name: Deploy Loki using the default configuration
   hosts: loki
   become: true
   roles:
    - role: grafana.grafana.loki
      tags: loki      
```
In this example, the `loki` tag is applied to the **entire role**. When you execute this playbook with the `-t loki` option, all tasks within the role, including uninstall tasks, will be executed.

**Comment by loliee** [comment]
I think this implementation is **fragile and error-prone**.

Having the uninstall feature is nice but it's far from crucial especially for production systems!

That said I think **you should really consider** the following scenario:
- This role is included in an instance group with a tag (like I did).
- The role is deployed without a tag on the instance group (everything works as expected).
- An operator introduces a configuration change and decides to deploy it using the tag in order to speed up delivery (He deletes the service).
- If the operator blindly believes in the return code of his command without looking at the output he will think that his modification was delivered successfully and this can lead to a catastrophic situation…

In many cases it is relatively simple to detect an absence of logs but this is not always the case and many do not have this kind of check.

Even if it is still possible to create specific groups to work around this problem, it requires more effort. And this is particularly true for the Promtail service which must be deployed on many groups of instances.

As a user **I had a bad experience using these roles (loki & promtail)**, and it's only because of this uninstallation feature (I also noticed that the APT repository was not deleted).

That's why I cannot use those roles in production…

In any case, thank you very much for all this work!

**Comment by voidquark** [comment]
Sorry, but I think there is nothing to implement in this PR except for the typo you mentioned. The role uninstallation is only executed when you run the specific tag. There is no way that this role will uninstall your Promtail or Loki instance unless you specifically request it. I have referred to the official Ansible documentation a couple of times, so the tag implementation is correct. The “never” tag is being used properly.

**Comment by voidquark** [comment]
Additionally, for reference, there is an Ansible issue (https://github.com/ansible/ansible/issues/40400) that describes your behavior. It is expected that Ansible operates in this manner. I strongly recommend revisiting your environment and the approach you are implementing. You are likely not the only one who finds this confusing.

**Comment by voidquark** [comment]
@loliee, do you plan to create another PR to fix the typos you mentioned in this PR?

**Comment by voidquark** [comment]
Fixed by - https://github.com/grafana/grafana-ansible-collection/pull/253

**Pull request closed without merging**
